### ISSUE TITLE
There's a box visible behind the rounded corners

### ISSUE THREAD

**Issue by BLUEChester** [O-RONI/TrueWin11Dark#2]
Hey, would love if the box behind the rounded corners could be removed, its triggering my OCD

![Arc_PJ3HaDHrco](https://github.com/user-attachments/assets/02ca4084-51f6-41fd-9619-723f4f106ca4)

Thanks!

**Comment by okrroni** [comment]
That's because the way the blur effect is rendered. All other themes with blur have the same issue...

I'm unable to fix this at the moment, but if you find it too annoying you could try changing your theme to one with no blur effect. I made this other version just for that: [TrueWindowsDark-Solid.xaml](https://github.com/okRoni/TrueWin11Dark/blob/main/TrueWin11Dark-Solid.xaml)

Have a great day!
